export const ServicesList = [
  {
    name: "Diagnóstico y prevención",
    image: "prevencion.webp",
    description: [
      "Consulta odontológica integral",
      "Evaluación clínica y planificación del tratamiento",
      "Radiografías y diagnóstico por imágenes",
      "Escaneo intraoral digital",
      "Profilaxis y limpieza dental",
      "Control periodontal",
    ],
  },
  {
    name: "Odontología restauradora",
    image: "restauradora.webp",
    description: [
      "Restauraciones estéticas en resina",
      "Reconstrucciones dentales",
      "Incrustaciones inlay, onlay y overlay",
      "Tratamiento de caries",
      "Cambio de restauraciones defectuosas",
      "Reconstrucción de dientes tratados endodónticamente",
    ],
  },
  {
    name: "Estética dental",
    image: "esteticadental.webp",
    description: [
      "Blanqueamiento dental en consultorio",
      "Carillas de resina",
      "Carillas cerámicas",
      "Diseño digital de sonrisa",
      "Cierre de espacios y correcciones estéticas",
      "Mock-up o prueba previa de la sonrisa",
    ],
  },
  {
    name: "Prótesis fija",
    image: "Protesis.webp",
    description: [
      "Coronas de zirconio",
      "Coronas de disilicato de litio",
      "Coronas metal-cerámica",
      "Puentes dentales",
      "Postes de fibra de vidrio",
      "Prótesis fija sobre dientes naturales",
    ],
  },
  {
    name: "Prótesis removible",
    image: "protesisremovible.webp",
    description: [
      "Prótesis total",
      "Prótesis parcial acrílica",
      "Prótesis parcial flexible",
      "Prótesis parcial removible de cromo-cobalto",
      "Prótesis inmediata",
      "Rebasado, reparación y mantenimiento de prótesis",
    ],
  },
  {
    name: "Implantología",
    image: "implantologia.webp",
    description: [
      "Planificación digital de implantes",
      "Colocación de implantes dentales",
      "Cirugía guiada",
      "Regeneración ósea",
      "Coronas y puentes sobre implantes",
      "Rehabilitaciones All-on-4 y All-on-6",
    ],
  },
  {
    name: "Periodoncia",
    image: "periodoncia.webp",
    description: [
      "Tratamiento de gingivitis",
      "Raspado y alisado radicular",
      "Tratamiento periodontal",
      "Cirugía periodontal",
      "Gingivectomía y alargamiento de corona",
      "Injertos de encía",
    ],
  },
  {
    name: "Endodoncia",
    image: "endodoncia.webp",
    description: [
      "Tratamiento de conductos",
      "Retratamiento endodóntico",
      "Tratamiento de urgencias pulpares",
      "Reconstrucción posterior a endodoncia",
      "Cirugía endodóntica, cuando esté indicada",
    ],
  },
  {
    name: "Cirugía oral",
    image: "cirugiaoral.webp",
    description: [
      "Extracciones simples",
      "Extracciones quirúrgicas",
      "Cirugía de terceros molares",
      "Regularización ósea",
      "Frenectomías",
      "Biopsias y manejo de lesiones orales",
    ],
  },
  {
    name: "Ortodoncia",
    image: "ortodoncia2.webp",
    description: [
      "Ortodoncia convencional",
      "Brackets estéticos",
      "Ortodoncia autoligable",
      "Alineadores transparentes",
      "Ortodoncia preventiva e interceptiva",
      "Retenedores",
    ],
  },
  {
    name: "Odontopediatría",
    image: "odontopediatria2.webp",
    description: [
      "Primera consulta infantil",
      "Prevención y control de caries",
      "Restauraciones pediátricas",
      "Tratamientos pulpares",
      "Mantenedores de espacio",
      "Manejo de traumatismos dentales",
    ],
  },
  {
    name: "Oclusión y trastornos temporomandibulares",
    image: "oclusion.webp",
    description: [
      "Evaluación de bruxismo",
      "Férulas de descarga",
      "Protectores deportivos",
      "Ajuste oclusal",
      "Manejo inicial de dolor muscular y articular",
      "Rehabilitación de pacientes con desgaste dental",
    ],
  },
];
